### ISSUE TITLE
SSL connection logging

### ISSUE THREAD

**Issue by goetzk** [mrlesmithjr/ansible-squid#10]
Hi,
I was wondering if your role supported SSL Peeking, It (AIUI) allows logging of connections , even though Squid can't decrypt the traffic.
https://wiki.squid-cache.org/Features/SslPeekAndSplice

thanks,

**Comment by mrlesmithjr** [comment]
@goetzk Unfortunately not at this time.

**Comment by goetzk** [comment]
Shame! Do you know how hard it works be to implement?

On 5 January 2018 11:50:49 am AEDT, "Larry Smith Jr." <notifications@github.com> wrote:
>@goetzk Unfortunately not at this time.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrlesmithjr/ansible-squid/issues/10#issuecomment-355442893

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mrlesmithjr** [comment]
I have never used it so not sure of the effort involved.

**Comment by goetzk** [comment]
For the record, here is a quick summary:

- To do peek/splice/bump you need to recompile squid with ssl support (see also #18). For anyone interested, its a relatively small number of steps to rebuild the Debian package.
- configure squid (squid_http_access, squid_acl_safeports, ....)
- add ACLs and so on as required. Example:
```
squid_acl:
  # For SSL inspection
  - name: step1
    type: at_step
    arg:  SslBump1
  - name: step2
    type: at_step
    arg:  SslBump2
  - name: SSL_ports
    type: port
    arg:  443
  - name: CONNECT
    type: method
    arg:  CONNECT
  - name: puppet_apt_repo_ssl
    type: ssl::server_name
    arg: apt.puppetlabs.com
```
- peek and bump actions from PR #19
```
squid_ssl_bump:
  - action: peek
    acl:
      - all
  - action: bump
    acl:
      - all
```

This allows logging and restricting SSL connections, though not logging the specific files/streams being transferred over the SSL connection. It also avoids the need to decrypt peoples traffic, or be seen to decrypt it.

Karl.
